### ISSUE TITLE
asic2tex.sh

### ISSUE THREAD

**Issue by jjts** [IObundle/iob-lib#158]
This script is wrongly named and should be converted to a python script (because python3 is called in most lines )  and moved into software/python temporarily

Correct name: genus2tex.py  (it only supports this tool and not asics in general)

Later, when there is a proper asic flow it should be moved to the build directory

**Comment by JDLopes** [comment]
I understand your comments, but the name asic2tex was chosen because this script was meant to be upgraded to support skywater tech node. Said that I will make the proposed changes.

**Comment by jjts** [comment]
No relation to node, only the synthesis tool. Any node will do. You are
processing the log of a synthesis tool that is tech-independent.   We also
have vivado2tex.sh and quartus2tex.sh...





Com os melhores cumprimentos / Best regards,

Jose T. de Sousa

**Comment by JDLopes** [comment]
Done!
