### ISSUE TITLE
missing $(LIB_DIR)/ prefix

### ISSUE THREAD

**Issue by jjts** [IObundle/iob-lib#161]
setup now runs from the core directory and not from the lib directory 

Hence, for all hardware.mk files, the above prefix must be added to all lib files to be copied to the core build directory. This has already been done for the hardware.mk lib files used by iob-cache

See hardware/ram/iob_ram_sp/hardware.mk for instance. Test and update iob-uart after this is done.

**Comment by JDLopes** [comment]
Done!
