### ISSUE TITLE
Why generate files in core root directory instead of directly in BUILD_LIB?

### ISSUE THREAD

**Issue by jjts** [IObundle/iob-lib#257]
A failed attempt to enable the incremental setup.

To make this possible, generation scripts should specify the destination directory.
Another improvement is to infer what to generate from the output file name since the name of what to generate is part of the output file name anyway.

**Comment by jjts** [comment]
--out-dir for example

**Comment by PedroAntunes178** [comment]
Addressed in PR https://github.com/IObundle/iob-lib/pull/264.

**Comment by P-Miranda** [comment]
we should also add this `--out-dir` flag to other scripts that generate output files, like `if_gen.py`

**Comment by jjts** [comment]
@arturum1, can this be closed?

**Comment by arturum1** [comment]
This can be closed. Currently, all files are generated in the build directory.
