### ISSUE TITLE
mkregs new flag to prevent address overlaps

### ISSUE THREAD

**Issue by jjts** [IObundle/iob-lib#263]
--no-overlap

**Comment by P-Miranda** [comment]
*overlap between read register addresses and write register addresses

**Comment by jjts** [comment]
an overlap check has been added 

need flag now

**Comment by jjts** [comment]
@arturum1, this is fixed, right?

**Comment by arturum1** [comment]
Yes, the `compute_addr(table, no_overlap)` function of mkregs.py receives the boolean `no_overlap` argument to do this.

**Comment by arturum1** [comment]
Currently, the LIB/scripts/setup.py calls the `compute_addr` function with always with `no_overlap=True`.
Should we add an argument to the `setup()` function of the setup.py file, to allow configuring this?
The flag `--no-overlap` is not used, as neither setup.py or mkregs.py are executed directly (with flags). They are imported into other modules that call the functions using arguments (without flags).

**Comment by jjts** [comment]
The iob user chooses whether address overlap is tolerated or not.  Please
do.

**Comment by arturum1** [comment]
The user can already configure if address overlap is tolerated by passing the argument `no_overlap` to the `setup()` function in the core configuration file (`<corename>_setup.py`).
Do you still want me to implement the `--no-overlap` flag as a command line argument? If so, which python script should parse this? (Neither `setup.py` nor `mkregs.py` are called from the command line as they dont have a main function, so they do not accept flags)

**Comment by jjts** [comment]
This fine. Thanks. No need for command line argument.
