### ISSUE TITLE
remove flag -f from console

### ISSUE THREAD

**Issue by jjts** [IObundle/iob-lib#413]
and let it respond to requests only

**Comment by PedroAntunes178** [comment]
Solved this issue in my fork.
Will push it in my next PR.

**Comment by jjts** [comment]
is this fixed then?

**Comment by PedroAntunes178** [comment]
> is this fixed then?

This is fixed in iob-lib/python-setup. Should the same changes be applied to master branch?

**Comment by jjts** [comment]
No, the master branch will have these changes when this branch is merged into it.
